/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AdvertiserProduct;

import Business.Validation.Validation;
import business.EcoSystem;
import business.Organization.AdvertiserProduct;
import business.Organization.DemandSidePlatform;
import business.enterprise.Advertiser;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Krush
 */
public class ProductManagerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ProductManagerWorkArea
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private AdvertiserProduct organization;
    private Advertiser enterprise;
    private EcoSystem system;

    String name;
    public ProductManagerWorkArea(JPanel userProcessContainer, UserAccount userAccount, AdvertiserProduct organization, Advertiser enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;

        productNamejTextField1.setEnabled(false);
        pricejTextField2.setEnabled(false);
        addjButton1.setEnabled(false);
        categoryjComboBox1.setEnabled(false);
        quantityjTextField1.setEnabled(false);
        pnamejTextField1.setEnabled(false);
        urljTextField1.setEnabled(false);
       
        namejLabel6.setText(enterprise.getName());
        
        populateFields();
       

    }
    
    public void populateFields(){
        categoryjComboBox1.removeAllItems();
         productNamejTextField1.setText(enterprise.getProduct().getProductName());
        pricejTextField2.setText(String.valueOf(enterprise.getProduct().getProductPrice()));
        quantityjTextField1.setText(String.valueOf(enterprise.getProduct().getQuantity()));
        urljTextField1.setText(enterprise.getProduct().getUrl());
        
        pnamejTextField1.setText(enterprise.getProduct().getCategory());
          String category[] = {"Shoes","Phones","HeadPhones","Books","Magazines","Watches"};
         for(int i =0 ; i< category.length; i++){
             categoryjComboBox1.addItem(category[i]);
         }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productNamejTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pricejTextField2 = new javax.swing.JTextField();
        addjButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        categoryjComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        quantityjTextField1 = new javax.swing.JTextField();
        pnamejTextField1 = new javax.swing.JTextField();
        urljTextField1 = new javax.swing.JTextField();
        namejLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Create Product");

        jLabel2.setText("Product Name");

        productNamejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNamejTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Product Price");

        pricejTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricejTextField2ActionPerformed(evt);
            }
        });

        addjButton1.setText("ADD");
        addjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButton1ActionPerformed(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Product Category");

        categoryjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Product Quantity");

        namejLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namejLabel6.setText("jLabel6");

        jLabel7.setText("URL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(110, 110, 110)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(urljTextField1)
                                            .addComponent(productNamejTextField1)
                                            .addComponent(categoryjComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(quantityjTextField1)
                                            .addComponent(pricejTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(namejLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(namejLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(categoryjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(quantityjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pricejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urljTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(addjButton1))
                .addGap(166, 166, 166))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productNamejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNamejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNamejTextField1ActionPerformed

    private void addjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButton1ActionPerformed
        // TODO add your handling code here:

        if(productNamejTextField1.getText().equals("") || pricejTextField2.getText().equals("")
                || quantityjTextField1.getText().equals("")|| urljTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill all the values");
            return;
        }
        
        if(Validation.checkInteger(pricejTextField2.getText())==false || Validation.checkInteger(quantityjTextField1.getText())==false){
            JOptionPane.showMessageDialog(null,"Enter Only Integer Values");
            return;
        }
        
        
        
        String name = productNamejTextField1.getText();
        int price = Integer.parseInt(pricejTextField2.getText());
         String category = (String) categoryjComboBox1.getSelectedItem();
         int quantity = Integer.parseInt(quantityjTextField1.getText());
            String url = urljTextField1.getText();
            
            
            if(price <= 0 || quantity <= 0){
            JOptionPane.showMessageDialog(null,"Values cannot be less than or equal to zero");
            return;
        }
             //name = category;
        enterprise.getProduct().setProductName(name);
        enterprise.getProduct().setProductPrice(price);
        enterprise.getProduct().setCategory(category);
        enterprise.getProduct().setQuantity(quantity);
        enterprise.getProduct().setUrl(url);
       
        populateFields();
        
        JOptionPane.showMessageDialog(null,"Product succssfully created");
        
        productNamejTextField1.setEnabled(false);
        pricejTextField2.setEnabled(false);
        quantityjTextField1.setEnabled(false);
        urljTextField1.setEnabled(false);

    }//GEN-LAST:event_addjButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int dialogButton = JOptionPane.showConfirmDialog(null, "Do you want to Add or Change Product Details..??", "Warning", JOptionPane.YES_NO_OPTION);

        if (dialogButton == JOptionPane.YES_OPTION) {
            productNamejTextField1.setEnabled(true);
            pricejTextField2.setEnabled(true);
            addjButton1.setEnabled(true);
            categoryjComboBox1.setEnabled(true);
            quantityjTextField1.setEnabled(true);
            urljTextField1.setEnabled(true);
            
            int price = Integer.parseInt(pricejTextField2.getText());
            String name = productNamejTextField1.getText();
            String category = (String) categoryjComboBox1.getSelectedItem();
             int quantity = Integer.parseInt(quantityjTextField1.getText());
             
             String url = urljTextField1.getText();
             
               if(productNamejTextField1.getText().equals("") || pricejTextField2.getText().equals("")
                || quantityjTextField1.getText().equals("")|| urljTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill all the values");
            return;
        }
        
        if(Validation.checkInteger(pricejTextField2.getText())==false || Validation.checkInteger(quantityjTextField1.getText())==false){
            JOptionPane.showMessageDialog(null,"Enter Only Integer Values");
            return;
        }
            
             enterprise.getProduct().setUrl(url);
            enterprise.getProduct().setProductName(name);
            enterprise.getProduct().setProductPrice(price);
            enterprise.getProduct().setCategory(category);
            enterprise.getProduct().setQuantity(quantity);
                    
            return;

        } else if (dialogButton == JOptionPane.NO_OPTION) {
            productNamejTextField1.setEnabled(false);
            pricejTextField2.setEnabled(false);
            addjButton1.setEnabled(false);
            categoryjComboBox1.setEnabled(false);
            quantityjTextField1.setEnabled(false);
            urljTextField1.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pricejTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricejTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricejTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton1;
    private javax.swing.JComboBox categoryjComboBox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel namejLabel6;
    private javax.swing.JTextField pnamejTextField1;
    private javax.swing.JTextField pricejTextField2;
    private javax.swing.JTextField productNamejTextField1;
    private javax.swing.JTextField quantityjTextField1;
    private javax.swing.JTextField urljTextField1;
    // End of variables declaration//GEN-END:variables
}
