/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CustomerRole;

import business.Customer.Customer;
import business.EcoSystem;
import business.Exchange.AdSpace;
import business.Exchange.Bid;
import business.Organization.Organization;
import business.WorkQueue.RequestPublisherWebsite;
import business.enterprise.AdExchange;
import business.enterprise.Enterprise;
import business.enterprise.Publisher;
import business.network.Network;
import business.userAccount.UserAccount;
import java.awt.Canvas;
import java.awt.CardLayout;
import javax.swing.JPanel;
import static sun.security.krb5.internal.KDCOptions.with;

/**
 *
 * @author Krush
 */
public class CustomerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkArea
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise1;
    private Enterprise enterprise;
    private EcoSystem system;
    private Bid bid;
    private Bid bid1;

    public CustomerWorkArea(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;

        searchjComboBox1.removeAllItems();
        String search[] = {"Shoes", "Phones", "HeadPhones", "Books", "Magazines", "Watches"};
        for (int i = 0; i < search.length; i++) {
            searchjComboBox1.addItem(search[i]);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        facebookjButton1 = new javax.swing.JButton();
        goToYahoojButton2 = new javax.swing.JButton();
        searchjComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customer Work Area");

        facebookjButton1.setText("Go to Facebook");
        facebookjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebookjButton1ActionPerformed(evt);
            }
        });

        goToYahoojButton2.setText("Go to Yahoo!");
        goToYahoojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToYahoojButton2ActionPerformed(evt);
            }
        });

        searchjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        searchjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Krush\\Desktop\\google.jpg")); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(facebookjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(goToYahoojButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facebookjButton1)
                    .addComponent(goToYahoojButton2))
                .addGap(55, 55, 55)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(126, 126, 126))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void facebookjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebookjButton1ActionPerformed

        System.out.println(userAccount);
        AdExchange ax = null;
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                // System.out.println(enterprise);
                // for(Organization organization: enterprise.getOrganizationDir().getOrganizationList()){

                if (enterprise instanceof AdExchange) {
                    // org = organization;
                    ax = (AdExchange) enterprise;
                    // enterprise1 = enterprise;
                    //ax.getWorkQueue().getWorkRequestList().add(request);
                    // userAccount.getWorkQueue().getWorkRequestList().add(request);
                }
            }
        }
        if (ax != null) {
            for (Publisher p : ax.getPublisherList()) {
                if (p.getName().equals("facebook")) {
                    for (AdSpace ad : p.getSsp().getAdSpaceList()) {

                        if (ad.getAvailStatus().equals("Available") && ad.getPosition().equals("TopRight")) {
                            Publisher publisher = p;
                            String position = ad.getPosition();
                            int basePrice = ad.getPrice();
                            bid = ax.requestBid(userAccount, system, ax, publisher, position, basePrice);
                            RequestPublisherWebsite request = new RequestPublisherWebsite();
                            request.setBid(bid);
                            request.setPublisher(publisher);
                            request.setPublisherName(publisher.getName());
                            request.setSender(userAccount);
                            ax.getWorkQueue().getWorkRequestList().add(request);
                            //bid1 = null;
                        }
                        if (ad.getAvailStatus().equals("Available") && ad.getPosition().equals("RightBottom")) {
                            String position = ad.getPosition();
                            Publisher publisher = p;
                            int basePrice = ad.getPrice();

                            bid1 = ax.requestBid(userAccount, system, ax, publisher, position, basePrice);
                            RequestPublisherWebsite request = new RequestPublisherWebsite();
                            request.setBid1(bid1);
                            //request.setBid(bid);
                            request.setPublisher(publisher);
                            request.setPublisherName(publisher.getName());
                            request.setSender(userAccount);
                            ax.getWorkQueue().getWorkRequestList().add(request);
                            //  bid = null;
                        }
                        /*else if ((ad.getAvailStatus().equals("Available") && ad.getPosition().equals("Right Bottom"))
                         && (ad.getAvailStatus().equals("Available") && ad.getPosition().equals("Top Right"))) {

                         bid = AdExchange.RequestBid(userAccount, system, ax);
                         bid1 = AdExchange.RequestBid(userAccount, system, ax);
                         // bid = null;
                         }
                         */

                    }
                }

            }

        }

        GotoFacebook cajp = new GotoFacebook(userProcessContainer, userAccount, organization, enterprise1, system, bid, bid1);
        userProcessContainer.add("CustomerAdJPanel", cajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_facebookjButton1ActionPerformed

    private void goToYahoojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToYahoojButton2ActionPerformed
        // TODO add your handling code here:

        System.out.println(userAccount);
        AdExchange ax = null;
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                // System.out.println(enterprise);
                // for(Organization organization: enterprise.getOrganizationDir().getOrganizationList()){

                if (enterprise instanceof AdExchange) {
                    // org = organization;
                    ax = (AdExchange) enterprise;
                    // enterprise1 = enterprise;
                    // ax.getWorkQueue().getWorkRequestList().add(request);
                    //userAccount.getWorkQueue().getWorkRequestList().add(request);
                }
            }
        }
        if (ax != null) {
            for (Publisher p : ax.getPublisherList()) {
                if (p.getName().equals("yahoo")) {
                    for (AdSpace ad : p.getSsp().getAdSpaceList()) {

                        if (ad.getAvailStatus().equals("Available") && ad.getPosition().equals("Center")) {

                            Publisher publisher = p;
                            String position = ad.getPosition();
                            int basePrice = ad.getPrice();

                            bid = ax.requestBid(userAccount, system, ax, publisher, position, basePrice);
                                    //bid1 = null;
                            //request.setBid(bid);
                            RequestPublisherWebsite request = new RequestPublisherWebsite();

                            request.setBid(bid);
                            request.setPublisher(publisher);
                            request.setPublisherName(publisher.getName());
                            request.setSender(userAccount);
                            ax.getWorkQueue().getWorkRequestList().add(request);
                        }
                        if (ad.getAvailStatus().equals("Available") && ad.getPosition().equals("LeftBottom")) {
                            String position = ad.getPosition();
                            Publisher publisher = p;
                            int basePrice = ad.getPrice();
                            bid1 = ax.requestBid(userAccount, system, ax, publisher, position, basePrice);
                                  //  bid = null;

                            RequestPublisherWebsite request = new RequestPublisherWebsite();
                            request.setBid1(bid1);
                            //request.setBid(bid);
                            request.setPublisher(publisher);
                            request.setPublisherName(publisher.getName());
                            request.setSender(userAccount);

                            //request.setBid(bid1);
                            ax.getWorkQueue().getWorkRequestList().add(request);
                        }

                    }
                }

            }

        }

        GotoYahoo gty = new GotoYahoo(userProcessContainer, userAccount, organization, enterprise1, system, bid, bid1);
        userProcessContainer.add("GotoYahoo", gty);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_goToYahoojButton2ActionPerformed

    private void searchjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchjComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String search = (String) searchjComboBox1.getSelectedItem();
        Customer c = userAccount.getCustomer();
        userAccount.getCustomer().addBrowsingHistory(search, c);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton facebookjButton1;
    private javax.swing.JButton goToYahoojButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox searchjComboBox1;
    // End of variables declaration//GEN-END:variables
}
