/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CustomerRole;

import business.Customer.Customer;
import business.EcoSystem;
import business.Exchange.Bid;
import business.Organization.Organization;
import business.enterprise.AdExchange;
import business.enterprise.Advertiser;
import business.enterprise.Enterprise;
import business.network.Network;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Krush
 */
public class OrderProduct extends javax.swing.JPanel {

    /**
     * Creates new form OrderProduct
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private JFrame frame;
    private Bid bid;
    private Bid bid1;
    private Customer c;
    boolean flag = false;

    public OrderProduct(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem system, Bid bid) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.c = userAccount.getCustomer();
        this.organization = organization;
        this.enterprise = enterprise;
        this.bid = bid;
        this.bid1 = bid1;
        this.system = system;

        namejTextField1.setEnabled(false);
        pricejTextField2.setEnabled(false);
        amountjTextField3.setEnabled(false);
        populateFields();
    }

    public void populateFields() {

        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof AdExchange) {
                    AdExchange ax = (AdExchange) e;
                    for (Advertiser a : ax.getAdvertiserList()) {
                        if (bid.getAdvertiserName().equals(a.getName())) {

                            namejTextField1.setText(a.getProduct().getProductName());
                            pricejTextField2.setText(String.valueOf(a.getProduct().getProductPrice()));

                            advertiserNamejLabel6.setText(a.getName());

                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namejTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pricejTextField2 = new javax.swing.JTextField();
        quantityjSpinner1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        amountjTextField3 = new javax.swing.JTextField();
        checkoutjButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addToCartjButton3 = new javax.swing.JButton();
        advertiserNamejLabel6 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cartjLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("     Shopping Cart");

        jLabel2.setText("Product Name");

        namejTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setText("Product Price");

        jLabel5.setText("Quantity");

        pricejTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setText("Total Amount");

        amountjTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        checkoutjButton1.setText("CheckOut");
        checkoutjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutjButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Krush\\Desktop\\Back-icon1.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        addToCartjButton3.setText("Add to Cart");
        addToCartjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartjButton3ActionPerformed(evt);
            }
        });

        advertiserNamejLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Krush\\Desktop\\Ecommerce-Shopping-Cart-icon.png")); // NOI18N
        jLabel6.setText("jLabel6");

        cartjLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cartjLabel7.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201)
                .addComponent(advertiserNamejLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartjLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(addToCartjButton3)))
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(checkoutjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(amountjTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityjSpinner1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pricejTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namejTextField1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(advertiserNamejLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cartjLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pricejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(quantityjSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amountjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkoutjButton1)
                    .addComponent(addToCartjButton3))
                .addGap(125, 125, 125))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutjButton1ActionPerformed
        // TODO add your handling code here:

        if (flag == true) {

            quantityjSpinner1.setEnabled(false);
            for (Network n : system.getNetworkList()) {
                for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                    if (e instanceof AdExchange) {
                        AdExchange ax = (AdExchange) e;
                        for (Advertiser a : ax.getAdvertiserList()) {
                            if (bid.getAdvertiserName().equals(a.getName())) {

                                int q = (int) quantityjSpinner1.getValue();

                              // int amnt = q * a.getProduct().getProductPrice();
                                if(bid.getPosition().equals("TopRight")){
                                a.getDsp().setClickp(a.getDsp().getClickp() + 1);
                                a.getDsp().setAmnt(a.getDsp().getAmnt() + (q * a.getProduct().getProductPrice()));
                                }
                                else if (bid.getPosition().equals("RightBottom")){
                                    a.getDsp().setClickp1(a.getDsp().getClickp1() + 1);
                                    a.getDsp().setAmnt1(a.getDsp().getAmnt1() + (q * a.getProduct().getProductPrice()));
                                }
                                
                                else if (bid.getPosition().equals("Center")){
                                    a.getDsp().setClickp2(a.getDsp().getClickp2()+1);
                                    a.getDsp().setAmnt2(a.getDsp().getAmnt2() + (q * a.getProduct().getProductPrice()));
                                   
                                }
                                 else if (bid.getPosition().equals("LeftBottom")){
                                     a.getDsp().setClickp3(a.getDsp().getClickp3()+1);
                                     a.getDsp().setAmnt3(a.getDsp().getAmnt3() + (q * a.getProduct().getProductPrice()));
                                 }

                              // a.getDsp().setAmnt(a.getDsp().getAmnt() + (q * a.getProduct().getProductPrice()));
                                a.getProduct().setQuantity(a.getProduct().getQuantity() - q);

                            }
                        }
                    }
                }
            }

            flag = false;
            JOptionPane.showMessageDialog(null, "Your Order has been CheckOut....ThankYou!!");

        } else {
            JOptionPane.showMessageDialog(null, "Add Some items to the Cart");
        }


    }//GEN-LAST:event_checkoutjButton1ActionPerformed

    private void addToCartjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartjButton3ActionPerformed
        // TODO add your handling code here:
        flag = true;
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof AdExchange) {
                    AdExchange ax = (AdExchange) e;
                    for (Advertiser a : ax.getAdvertiserList()) {
                        if (bid.getAdvertiserName().equals(a.getName())) {

                            int q = (int) quantityjSpinner1.getValue();

                            if ((q <= 0)) {
                                JOptionPane.showMessageDialog(null, "Please enter a correct Quantity, ");
                                return;
                            }

                            if (q > a.getProduct().getQuantity()) {
                                JOptionPane.showMessageDialog(null, "Only " + a.getProduct().getQuantity() + " Quantity Available");
                                return;
                            }

                            int amnt = q * a.getProduct().getProductPrice();
                            
                            cartjLabel7.setText(String.valueOf(q));
                            quantityjSpinner1.setEnabled(false);
                            amountjTextField3.setText(String.valueOf(amnt));

                            JOptionPane.showMessageDialog(null, "Quantity " + q + " Added to the Cart");

                           // a.getDsp().setClickp(a.getDsp().getClickp() + 1);

                           // a.getDsp().setAmnt(a.getDsp().getAmnt() + (q * a.getProduct().getProductPrice()));

                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_addToCartjButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (flag == true) {
            JOptionPane.showMessageDialog(null, "Your Order has not been processed, Order will be cancelled");
        }
        else{
            JOptionPane.showMessageDialog(null,"Thankyou!!!..Visit Again");
        }
            userProcessContainer.remove(this);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartjButton3;
    private javax.swing.JLabel advertiserNamejLabel6;
    private javax.swing.JTextField amountjTextField3;
    private javax.swing.JLabel cartjLabel7;
    private javax.swing.JButton checkoutjButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField namejTextField1;
    private javax.swing.JTextField pricejTextField2;
    private javax.swing.JSpinner quantityjSpinner1;
    // End of variables declaration//GEN-END:variables
}
