/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.PublisherMarketingRole;

import Business.Validation.Validation;
import business.EcoSystem;
import business.Exchange.AdSpace;
import business.Organization.Organization;
import business.Organization.SupplySidePlatform;
import business.WorkQueue.AdSpaceAvailable;
import business.enterprise.AdExchange;
import business.enterprise.Enterprise;
import static business.enterprise.Enterprise.EnterpriseType.Publisher;
import business.enterprise.Publisher;
import business.network.Network;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krush
 */
public class CreateAdSpace extends javax.swing.JPanel {

    /**
     * Creates new form CreateAdSpace
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SupplySidePlatform organization;
    private Publisher enterprise;
    private EcoSystem system;

    public CreateAdSpace(JPanel userProcessContainer, UserAccount userAccount, SupplySidePlatform organization, Publisher enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;

        populateCombo();
        //  populateTable();
    }

    /* public void populateTable() {
     DefaultTableModel dtm = (DefaultTableModel) adSpacejTable1.getModel();
     dtm.setRowCount(0);
     System.out.println(enterprise.getSsp());

     for (AdSpace adSpace : enterprise.getSsp().getAdSpaceList()) {
     Object row[] = new Object[3];
     row[0] = adSpace.getPosition();
     row[1]=  adSpace.getPrice();
     row[2]= adSpace.getAvailStatus();
     dtm.addRow(row);
     }

     }
     */
    public void populateCombo() {
        adSpacejComboBox1.removeAllItems();
        statusjComboBox1.removeAllItems();
        //  for(Organization org: enterprise.getOrganizationDir().getOrganizationList()){
        //    if(org instanceof SupplySidePlatform ){

        String status[] = {"Available", "Not Available"};
        for (int i = 0; i < status.length; i++) {
            statusjComboBox1.addItem(status[i]);
        }

        if (enterprise.getName().equalsIgnoreCase("facebook")) {

            for (AdSpace.AdSpaceType type : AdSpace.AdSpaceType.values()) {
                if (!type.getValue().equals(AdSpace.AdSpaceType.Center.getValue())
                        && !type.getValue().equals(AdSpace.AdSpaceType.LeftBottom.getValue())) {
                    adSpacejComboBox1.addItem(type);
                }

            }
        }
        
        if (enterprise.getName().equalsIgnoreCase("yahoo")) {

            for (AdSpace.AdSpaceType type : AdSpace.AdSpaceType.values()) {
                if (!type.getValue().equals(AdSpace.AdSpaceType.TopRight.getValue())
                        && !type.getValue().equals(AdSpace.AdSpaceType.RightBottom.getValue())) {
                    adSpacejComboBox1.addItem(type);
                }

            }
        }
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adSpacejComboBox1 = new javax.swing.JComboBox();
        addjButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pricejTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        statusjComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("AdSpace ");

        jLabel2.setText("Name");

        adSpacejComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addjButton1.setText("Add");
        addjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Base Price");

        jLabel4.setText("Status");

        statusjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/PublisherMarketingRole/6a00d8341c192953ef0120a51c4f50970b.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1))
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adSpacejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pricejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(addjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(adSpacejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(pricejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(statusjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)
                        .addComponent(addjButton1)
                        .addGap(112, 112, 112)))
                .addComponent(jButton2)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButton1ActionPerformed
        // TODO add your handling code here:
         if(pricejTextField1.getText().equals("") || adSpacejComboBox1==null){
             JOptionPane.showMessageDialog(null, "Pleas fill all the values");
             return;
         }
         
         if(Validation.checkInteger(pricejTextField1.getText())==false){
             JOptionPane.showMessageDialog(null,"Enter only Integer values");
             return;
         }
      
        int price = Integer.parseInt(pricejTextField1.getText());
        AdSpace.AdSpaceType type = (AdSpace.AdSpaceType) adSpacejComboBox1.getSelectedItem();
        String status = (String) statusjComboBox1.getSelectedItem();
        
  
        if (price <= 0) {
            JOptionPane.showMessageDialog(null, "Enter only valid values");
            return;
        }
        
        for(AdSpace ads : enterprise.getSsp().getAdSpaceList()){
            if(ads.getPosition().equals(type.getValue())){
                JOptionPane.showMessageDialog(null,"AdSpace Already added");
                return;
            }
        }
       
        
        enterprise.getSsp().createSpaceAvail(type, price, status,enterprise.getName());

        AdSpaceAvailable request = new AdSpaceAvailable();
        request.setSender(userAccount);
        request.setAdSpace(type);
        request.setPosition(type.getValue());
        request.setPublisherName(enterprise.getName());
        request.setStatus(status);

        AdExchange ax = null;
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {

                if (enterprise instanceof AdExchange) {
                    
                    ax = (AdExchange) enterprise;
                    ax.getWorkQueue().getWorkRequestList().add(request);
                    userAccount.getWorkQueue().getWorkRequestList().add(request);
                }

            }

        }
        // populateTable();
    }//GEN-LAST:event_addjButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox adSpacejComboBox1;
    private javax.swing.JButton addjButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pricejTextField1;
    private javax.swing.JComboBox statusjComboBox1;
    // End of variables declaration//GEN-END:variables
}
