/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.PublisherMarketingRole;

import Business.Validation.Validation;
import business.EcoSystem;
import business.Exchange.AdSpace;
import business.Organization.Organization;
import business.Organization.SupplySidePlatform;
import business.WorkQueue.AdSpaceAvailable;
import business.WorkQueue.WorkRequest;
import business.enterprise.AdExchange;
import business.enterprise.Enterprise;
import business.enterprise.Publisher;
import business.network.Network;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krush
 */
public class ManageAdSpace extends javax.swing.JPanel {

    /**
     * Creates new form ManageAdSpace
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SupplySidePlatform organization;
    private Publisher enterprise;
    private EcoSystem system;
    private AdSpace adSpace;

    public ManageAdSpace(JPanel userProcessContainer, UserAccount userAccount, SupplySidePlatform organization, Publisher enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;

        namejLabel2.setVisible(false);
        basepricejLabel3.setVisible(false);
        statusjLabel4.setVisible(false);
        adSpacejComboBox1.setVisible(false);
        pricejTextField1.setVisible(false);
        statusjComboBox1.setVisible(false);
        savejButton1.setVisible(false);

        populateTable();
        populateCombo();

    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) adSpacejTable1.getModel();
        dtm.setRowCount(0);
        System.out.println(enterprise.getSsp());

        for (AdSpace adSpace : enterprise.getSsp().getAdSpaceList()) {
            Object row[] = new Object[3];
            row[0] = adSpace;
            row[1] = adSpace.getPrice();
            row[2] = adSpace.getAvailStatus();
            dtm.addRow(row);
        }

    }

    public void populateCombo() {
        adSpacejComboBox1.removeAllItems();
        statusjComboBox1.removeAllItems();
        //  for(Organization org: enterprise.getOrganizationDir().getOrganizationList()){
        //    if(org instanceof SupplySidePlatform ){

        String status[] = {"Available", "Not Available"};
        for (int i = 0; i < status.length; i++) {
            statusjComboBox1.addItem(status[i]);
        }

        if (enterprise.getName().equals("yahoo")) {
            for (AdSpace.AdSpaceType type : AdSpace.AdSpaceType.values()) {

                if (!type.getValue().equals(AdSpace.AdSpaceType.TopRight.getValue()) && !type.getValue().equals(AdSpace.AdSpaceType.RightBottom.getValue())) {

                    adSpacejComboBox1.addItem(type);
                }
            }
        }

        if (enterprise.getName().equals("facebook")) {
            for (AdSpace.AdSpaceType type : AdSpace.AdSpaceType.values()) {
                if (!type.getValue().equals(AdSpace.AdSpaceType.Center.getValue()) && !type.getValue().equals(AdSpace.AdSpaceType.LeftBottom.getValue())) {
                    adSpacejComboBox1.addItem(type);
                }

            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adSpacejTable1 = new javax.swing.JTable();
        updatejButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        namejLabel2 = new javax.swing.JLabel();
        adSpacejComboBox1 = new javax.swing.JComboBox();
        basepricejLabel3 = new javax.swing.JLabel();
        pricejTextField1 = new javax.swing.JTextField();
        statusjLabel4 = new javax.swing.JLabel();
        statusjComboBox1 = new javax.swing.JComboBox();
        savejButton1 = new javax.swing.JButton();

        adSpacejTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "AdSpaces", "Base Price", "Availablity Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(adSpacejTable1);

        updatejButton1.setText("Update");
        updatejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        namejLabel2.setText("Position");

        adSpacejComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        basepricejLabel3.setText("Base Price");

        statusjLabel4.setText("Status");

        statusjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        savejButton1.setText("Save");
        savejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updatejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statusjLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(basepricejLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namejLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adSpacejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pricejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savejButton1)))
                    .addComponent(jButton2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatejButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(namejLabel2)
                                .addComponent(adSpacejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(basepricejLabel3)
                                .addComponent(pricejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(statusjLabel4))
                        .addComponent(statusjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(savejButton1)
                .addGap(45, 45, 45)
                .addComponent(jButton2)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButton1ActionPerformed
        // TODO add your handling code here:

        int dialogButton = JOptionPane.showConfirmDialog(null, "Do you want to Change the Status?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            namejLabel2.setVisible(true);
            basepricejLabel3.setVisible(true);
            statusjLabel4.setVisible(true);
            adSpacejComboBox1.setVisible(true);
            pricejTextField1.setVisible(true);
            statusjComboBox1.setVisible(true);
            savejButton1.setVisible(true);
            return;
        } else if (dialogButton == JOptionPane.NO_OPTION) {

            namejLabel2.setVisible(false);
            basepricejLabel3.setVisible(false);
            statusjLabel4.setVisible(false);
            adSpacejComboBox1.setVisible(false);
            pricejTextField1.setVisible(false);
            statusjComboBox1.setVisible(false);
            savejButton1.setVisible(false);
            return;
        }


    }//GEN-LAST:event_updatejButton1ActionPerformed

    private void savejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButton1ActionPerformed
        // TODO add your handling code here:

        int selectedRow = adSpacejTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a Row");
            return;
        }

        AdSpace adSpace = (AdSpace) adSpacejTable1.getValueAt(selectedRow, 0);

        if(pricejTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all the values");
            return;
        }
        
        if (Validation.checkInteger(pricejTextField1.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Enter only Integer values");
            return;
        }

        int price = Integer.parseInt(pricejTextField1.getText());
        AdSpace.AdSpaceType type = (AdSpace.AdSpaceType) adSpacejComboBox1.getSelectedItem();
        String status = (String) statusjComboBox1.getSelectedItem();

        if (price <= 0) {
            JOptionPane.showMessageDialog(null, "Enter only valid values");
            return;
        }
        
        
       for(AdSpace ads : enterprise.getSsp().getAdSpaceList()){
            if(!ads.getPosition().equals(type.getValue())){
                JOptionPane.showMessageDialog(null,"Cannot modify this adspace");
                return;
            }
        }
        

        adSpace.setPrice(price);
        adSpace.setPosition(type.getValue());
        adSpace.setAvailStatus(status);

        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {

                if (enterprise instanceof AdExchange) {
                    for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()) {
                        if (request instanceof AdSpaceAvailable) {
                            AdSpaceAvailable adreq = (AdSpaceAvailable) request;
                            adreq.setStatus(status);
                        }
                    }
                    // enterprise.getWorkQueue().getWorkRequestList().add(request);
                    // userAccount.getWorkQueue().getWorkRequestList().add(request);
                }

            }

        }

        populateTable();
    }//GEN-LAST:event_savejButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox adSpacejComboBox1;
    private javax.swing.JTable adSpacejTable1;
    private javax.swing.JLabel basepricejLabel3;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namejLabel2;
    private javax.swing.JTextField pricejTextField1;
    private javax.swing.JButton savejButton1;
    private javax.swing.JComboBox statusjComboBox1;
    private javax.swing.JLabel statusjLabel4;
    private javax.swing.JButton updatejButton1;
    // End of variables declaration//GEN-END:variables
}
