/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.PublisherMarketingRole;

import business.EcoSystem;
import business.Organization.Organization;
import business.Organization.SupplySidePlatform;
import business.enterprise.AdExchange;
import business.enterprise.Advertiser;
import business.enterprise.Enterprise;
import business.enterprise.Publisher;
import business.network.Network;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Krush
 */
public class SSPManagerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form SSPManagerWorkArea
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SupplySidePlatform organization;
    private Publisher enterprise;
    private EcoSystem system;

    public SSPManagerWorkArea(JPanel userProcessContainer, UserAccount userAccount, SupplySidePlatform organization, Publisher enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAdSpacejButton1 = new javax.swing.JButton();
        manageAdSpacejButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        createAdSpacejButton1.setText("Create AdSpace");
        createAdSpacejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAdSpacejButton1ActionPerformed(evt);
            }
        });

        manageAdSpacejButton2.setText("Manage AdSpace");
        manageAdSpacejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdSpacejButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Publisher Marketing WorkArea");

        jButton1.setText("View Clicks");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(manageAdSpacejButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createAdSpacejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(120, 120, 120)
                .addComponent(createAdSpacejButton1)
                .addGap(46, 46, 46)
                .addComponent(manageAdSpacejButton2)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createAdSpacejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAdSpacejButton1ActionPerformed
        // TODO add your handling code here:
        CreateAdSpace cas = new CreateAdSpace(userProcessContainer, userAccount, organization, enterprise, system);
        userProcessContainer.add("CreateAdSpace", cas);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_createAdSpacejButton1ActionPerformed

    private void manageAdSpacejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdSpacejButton2ActionPerformed
        // TODO add your handling code here:
        ManageAdSpace mas = new ManageAdSpace(userProcessContainer, userAccount, organization, enterprise, system);
        userProcessContainer.add("ManageAdSpace", mas);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAdSpacejButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int i = 0;
        DefaultCategoryDataset barChartData = new DefaultCategoryDataset();
        JFreeChart barChart = null;

        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof AdExchange) {
                    AdExchange ax = (AdExchange) e;

                    if (enterprise.getName().equals("facebook")) {

                        int topRight = 0;
                        int rightBottom = 0;
                        for (Advertiser a : ax.getAdvertiserList()) {
                            topRight = (int) (topRight + a.getDsp().getClicksObtained());
                            rightBottom = (int) (rightBottom + a.getDsp().getClicksObtained1());
                        }

                        barChartData.setValue(topRight, "ClicksObtained at TopRight", "TopRight");

                        barChartData.setValue(rightBottom, "ClicksObtained at RightBottom", "RightBottom");

                        barChart = ChartFactory.createBarChart("User Click Analysis", "AdSpace Position", "Clicks Obtained", barChartData, PlotOrientation.VERTICAL, true, true, true);
                        CategoryPlot bar = barChart.getCategoryPlot();
                        bar.setRangeGridlinePaint(Color.YELLOW);
                    } else {

                        int center = 0;
                        int leftBottom = 0;
                        for (Advertiser a : ax.getAdvertiserList()) {
                            center = (int) (center + a.getDsp().getClicksObtained2());
                            leftBottom = (int) (leftBottom + a.getDsp().getClicksObtained3());
                        }
                        barChartData.setValue(center, "Clicks Obtained", "Center");

                        barChartData.setValue(leftBottom, "ClicksObtained", "LeftBottom");

                        barChart = ChartFactory.createBarChart("User Click Analysis", "AdSpace Position", "Clicks Obtained", barChartData, PlotOrientation.VERTICAL, true, true, true);
                        CategoryPlot bar = barChart.getCategoryPlot();
                        bar.setRangeGridlinePaint(Color.YELLOW);
                    }

                }
            }
        }

          ChartFrame frame = new ChartFrame(" Click Chart", barChart);
        frame.setVisible(true);
        frame.setSize(500, 500);

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAdSpacejButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAdSpacejButton2;
    // End of variables declaration//GEN-END:variables
}
