/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.AdministrativeRole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Krush
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanell
     */
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem system;
    public AdminWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise, EcoSystem system ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise= enterprise;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageOrganozationjButton1 = new javax.swing.JButton();
        manageEmployeejButton2 = new javax.swing.JButton();
        manageUserjButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Administrative Work Area");

        manageOrganozationjButton1.setText("Manage Organization");
        manageOrganozationjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganozationjButton1ActionPerformed(evt);
            }
        });

        manageEmployeejButton2.setText("Manage Employee");
        manageEmployeejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeejButton2ActionPerformed(evt);
            }
        });

        manageUserjButton3.setText("Manage User");
        manageUserjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserjButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageEmployeejButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageOrganozationjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageUserjButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1)))
                .addGap(219, 219, 219))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addComponent(manageOrganozationjButton1)
                .addGap(43, 43, 43)
                .addComponent(manageEmployeejButton2)
                .addGap(39, 39, 39)
                .addComponent(manageUserjButton3)
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrganozationjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganozationjButton1ActionPerformed
        // TODO add your handling code here:
        ManageOrganization mo = new ManageOrganization(userProcessContainer,enterprise, enterprise.getOrganizationDir(),system);
        userProcessContainer.add("ManageOrganization",mo);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageOrganozationjButton1ActionPerformed

    private void manageEmployeejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeejButton2ActionPerformed
        // TODO add your handling code here:
         ManageEmployee me = new ManageEmployee(userProcessContainer,enterprise.getOrganizationDir(),enterprise,system);
        userProcessContainer.add("ManageEmployee",me);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmployeejButton2ActionPerformed

    private void manageUserjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserjButton3ActionPerformed
        // TODO add your handling code here:
        ManageUser mu = new ManageUser(userProcessContainer,enterprise.getOrganizationDir(),system,enterprise);
        userProcessContainer.add("ManageUser",mu);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageUserjButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmployeejButton2;
    private javax.swing.JButton manageOrganozationjButton1;
    private javax.swing.JButton manageUserjButton3;
    // End of variables declaration//GEN-END:variables
}
