/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AdministrativeRole;

import business.AdvertiserFinance.AdvertiserFinanceManager;
import business.AdvertiserMareketing.DemandSidePlatFormManager;
import business.Customer.Customer;
import business.EcoSystem;
import business.Organization.Organization;
import business.Organization.OrganizationDirectory;
import business.Organization.PublisherFinance;
import business.PublisherFinance.PublisherFinanceManager;
import business.PublisherMarketing.SSPManager;
import business.employee.Person;
import business.enterprise.Enterprise;
import business.network.Network;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krush
 */
public class ManageEmployee extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployee
     */
    private JPanel userProcessContainer;
    private OrganizationDirectory organizationDir;
    private Enterprise enterprise;
    private EcoSystem system;

    public ManageEmployee(JPanel userProcessContainer, OrganizationDirectory organizationDir, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = organizationDir;
        this.enterprise = enterprise;
        this.system = system;
        populateDisplayCombobox();
        // populateEmployeeTable();
        populateOrgCombobox();
    }

    public void populateEmployeeTable(Organization organization) {

        DefaultTableModel dtm = (DefaultTableModel) employeejTable1.getModel();
        dtm.setRowCount(0);

        for (Person employee : organization.getPersonDir().getPersonList()) {
            Object row[] = new Object[2];
            row[0] = employee.getEmpId();
            row[1] = employee.getEmpName();
            dtm.addRow(row);

        }

    }

    public void populateDisplayCombobox() {
        displayOrgjComboBox1.removeAllItems();

        for (Organization organization : organizationDir.getOrganizationList()) {
            displayOrgjComboBox1.addItem(organization);
        }

    }

    public void populateOrgCombobox() {
        createOrgjComboBox2.removeAllItems();

        for (Organization organization : organizationDir.getOrganizationList()) {
            createOrgjComboBox2.addItem(organization);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employeejTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        displayOrgjComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        createOrgjComboBox2 = new javax.swing.JComboBox();
        namejTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        createEmployeejButton1 = new javax.swing.JButton();
        backjButton2 = new javax.swing.JButton();

        setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        employeejTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                " Employee ID", "Employee Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employeejTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Manage Employee");

        jLabel2.setText("Organization");

        displayOrgjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        displayOrgjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayOrgjComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Organization");

        createOrgjComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Name");

        createEmployeejButton1.setText("Create Employee");
        createEmployeejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeejButton1ActionPerformed(evt);
            }
        });

        backjButton2.setText("<< Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(displayOrgjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backjButton2)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(createOrgjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(86, 86, 86)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(createEmployeejButton1)
                                .addComponent(namejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel1)))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(displayOrgjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(createOrgjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(createEmployeejButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(backjButton2)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton2ActionPerformed

    private void displayOrgjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayOrgjComboBox1ActionPerformed
        // TODO add your handling code here:
        Organization organization = (Organization) displayOrgjComboBox1.getSelectedItem();
        if (organization != null) {
            populateEmployeeTable(organization);
        }
    }//GEN-LAST:event_displayOrgjComboBox1ActionPerformed

    private void createEmployeejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeejButton1ActionPerformed
        // TODO add your handling code here:
        Organization selectedOrg = (Organization) createOrgjComboBox2.getSelectedItem();
        String name = namejTextField1.getText();

        for (Person p : selectedOrg.getPersonDir().getPersonList()) {
            if (p.getEmpName().equalsIgnoreCase(name)) {
                JOptionPane.showMessageDialog(null, "Employee Name Already exists ");
                return;
            }

        }
        
        if(namejTextField1.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all the values");
            return;
        }

        if (selectedOrg.getName().equals("Publisher Finance")) {
            PublisherFinanceManager pf = new PublisherFinanceManager();
            pf.setEmpName(name);
            Person p = new Person();
            p = pf;

            selectedOrg.getPersonDir().getPersonList().add(p);
            populateEmployeeTable(selectedOrg);
            return;
        }
        if (selectedOrg.getName().equals("Supply Side Platform")) {
            SSPManager pmm = new SSPManager();
            pmm.setEmpName(name);
            Person p = new Person();
            p = pmm;

            selectedOrg.getPersonDir().getPersonList().add(p);
            populateEmployeeTable(selectedOrg);
            return;
        }
        if (selectedOrg.getName().equals("Advertiser Finance")) {
            AdvertiserFinanceManager afm = new AdvertiserFinanceManager();
            afm.setEmpName(name);
            Person p = new Person();
            p = afm;

            selectedOrg.getPersonDir().getPersonList().add(p);
            populateEmployeeTable(selectedOrg);
            return;
        }
       
        if (selectedOrg.getName().equals("Demand Side Platform")) {
            System.out.println(selectedOrg);
            DemandSidePlatFormManager dspm = new DemandSidePlatFormManager();
            dspm.setEmpName(name);
            Person p = new Person();
            p = dspm;

            selectedOrg.getPersonDir().getPersonList().add(p);
            populateEmployeeTable(selectedOrg);
            return;
        }
        if (selectedOrg.getName().equals("Customer Organization")) {
            Customer c = new Customer();
            c.setEmpName(name);
            Person p = new Person();
            p = c;

            selectedOrg.getPersonDir().getPersonList().add(p);
            populateEmployeeTable(selectedOrg);
            return;
        }
        if (selectedOrg.getName().equals("AdExchange Management")) {
                 // Customer c = new Customer();
            //c.setEmpName(name);
            Person p = new Person();
            // p = c;
            p.setEmpName(name);
            selectedOrg.getPersonDir().getPersonList().add(p);
            populateEmployeeTable(selectedOrg);
            return;
        }

        if (selectedOrg.getName().equals("Advertiser Product")) {
                 // Customer c = new Customer();
            //c.setEmpName(name);
            Person p = new Person();
            // p = c;
            p.setEmpName(name);
            selectedOrg.getPersonDir().getPersonList().add(p);
            populateEmployeeTable(selectedOrg);
            return;
        }


    }//GEN-LAST:event_createEmployeejButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton2;
    private javax.swing.JButton createEmployeejButton1;
    private javax.swing.JComboBox createOrgjComboBox2;
    private javax.swing.JComboBox displayOrgjComboBox1;
    private javax.swing.JTable employeejTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namejTextField1;
    // End of variables declaration//GEN-END:variables
}
