/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.AdExchange;

import business.EcoSystem;
import business.Exchange.AdSpace;
import business.Organization.AdExchangeOrganization;
import business.WorkQueue.AdSpaceAvailable;
import business.WorkQueue.RequestPublisherWebsite;
import business.WorkQueue.WorkRequest;
import business.enterprise.AdExchange;
import business.enterprise.Publisher;
import business.userAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krush
 */
public class AdExchangeWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form AdExchangeWorkArea
     */
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private AdExchangeOrganization organization;
    private AdExchange enterprise;
    public AdExchangeWorkArea(JPanel userProcessContainer,UserAccount userAccount, AdExchangeOrganization organization, AdExchange enterprise, EcoSystem system ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        
        populateTable();
        populateUserTable();
        
    }
   
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) adSpacejTable1.getModel();
        dtm.setRowCount(0);
       /* for(WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()){
            if(request instanceof AdSpaceAvailable){
                AdSpaceAvailable adreq = (AdSpaceAvailable) request;
                
                Object row[] = new Object[3];
                row[0]= adreq.getPublisherName();
                row[1]= adreq.getPosition();
                row[2]= adreq.getStatus();
                
                dtm.addRow(row);
            }
        }
        */
        
        for(Publisher p: enterprise.getPublisherList()){
           for(AdSpace ad : p.getSsp().getAdSpaceList()){
               Object row[] = new Object[4];
                row[0]= ad;
                row[1]= ad.getPosition();
                row[2]= ad.getPrice();
                row[3]= ad.getAvailStatus();
                
                dtm.addRow(row);
           }
    }
    }
    
    public void populateUserTable(){
        DefaultTableModel dtm = (DefaultTableModel) userjTable1.getModel();
        dtm.setRowCount(0);
        for(WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()){
            if(request instanceof RequestPublisherWebsite){
                RequestPublisherWebsite rePub = (RequestPublisherWebsite) request;
                Object row[] = new Object[5];
                String name = rePub.getSender().getCustomer().getName();
                row[0]= name;
                row[1] = rePub.getPublisherName();
                if(rePub.getBid()!= null){
                    row[2]= rePub.getBid().getPosition();
                    row[3]= rePub.getBid().getAdvertiserName();
                    row[4]= rePub.getBid().getBidAmount();
                }
                
                if(rePub.getBid1() !=null){
                    row[2]= rePub.getBid1().getPosition();
                    row[3]= rePub.getBid1().getAdvertiserName();
                    row[4]= rePub.getBid1().getBidAmount();
                }
                
                dtm.addRow(row);
                
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adSpacejTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userjTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("AdExchange Work Area");

        adSpacejTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Publisher", "AdSpace Position", "Base Price ", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(adSpacejTable1);

        jLabel3.setText("Publisher Details");

        userjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Publisher Website", "Ad Position", "Advertiser", "Winning Bid Amnt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(userjTable1);

        jLabel4.setText("UserAccount Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(876, 876, 876)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adSpacejTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable userjTable1;
    // End of variables declaration//GEN-END:variables
}
