/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AdvertiserMarketing;

import Business.Validation.Validation;
import business.EcoSystem;
import business.Exchange.AdSpace;
import business.Exchange.Bid;
import business.Organization.DemandSidePlatform;
import business.Organization.Organization;
import business.enterprise.AdExchange;
import business.enterprise.Advertiser;
import business.enterprise.Enterprise;
import business.enterprise.Publisher;
import business.network.Network;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Krush
 */
public class BiddingModel extends javax.swing.JPanel {

    /**
     * Creates new form AdvertiseBiddingModel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private DemandSidePlatform organization;
    private Advertiser advertiser;
    private EcoSystem system;

    public BiddingModel(JPanel userProcessContainer, UserAccount userAccount, DemandSidePlatform organization, Advertiser enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.advertiser = enterprise;
        this.system = system;

        populateCombobox();

    }

    public void populateCombobox() {
        positionjComboBox1.removeAllItems();
        hobbiesjComboBox1.removeAllItems();
        publisherjComboBox1.removeAllItems();
        lastSearchedjComboBox1.removeAllItems();
        countryjComboBox1.removeAllItems();

        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof AdExchange) {
                    AdExchange ax = (AdExchange) e;
                    for (Publisher p : ax.getPublisherList()) {
                        publisherjComboBox1.addItem(p);
                    }
                }
            }
        }

        String lastSearched[] = {"Shoes", "Phones", "HeadPhones", "Books", "Magazines", "Watches"};
        for (int i = 0; i < lastSearched.length; i++) {
            lastSearchedjComboBox1.addItem(lastSearched[i]);
        }

        String hobbies[] = {"Sports", "Music", "Reading"};
        for (int j = 0; j < hobbies.length; j++) {
            hobbiesjComboBox1.addItem(hobbies[j]);
        }
        
        String country[] = {"India","US", "China"};
        for(int i = 0; i<country.length; i++){
            countryjComboBox1.addItem(country[i]);
        }
        // }
    }

    public void populatePositionCombo(Publisher p) {
        positionjComboBox1.removeAllItems();
        for (AdSpace type : p.getSsp().getAdSpaceList()) {
            positionjComboBox1.addItem(type);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bidAmountjTextField5 = new javax.swing.JTextField();
        setBidjButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        browsejButton1 = new javax.swing.JButton();
        filepathjTextField1 = new javax.swing.JTextField();
        minAgejTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        maxAgejTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        positionjComboBox1 = new javax.swing.JComboBox();
        backjButton1 = new javax.swing.JButton();
        hobbiesjComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        publisherjComboBox1 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        lastSearchedjComboBox1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        minScorejTextField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        maxScorejTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        countryjComboBox1 = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Min. Age");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 153, -1, -1));

        jLabel2.setText("Hobbies");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 191, -1, -1));

        bidAmountjTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidAmountjTextField5ActionPerformed(evt);
            }
        });
        add(bidAmountjTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 369, 199, 23));

        setBidjButton1.setText("Set Bid");
        setBidjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBidjButton1ActionPerformed(evt);
            }
        });
        add(setBidjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 468, 98, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bid Values");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 11, -1, -1));

        jLabel5.setText("BidAmount");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 369, 82, 23));

        browsejButton1.setText("Browse");
        browsejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsejButton1ActionPerformed(evt);
            }
        });
        add(browsejButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 410, 76, -1));

        filepathjTextField1.setEnabled(false);
        filepathjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filepathjTextField1ActionPerformed(evt);
            }
        });
        add(filepathjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 199, 23));

        minAgejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minAgejTextField1ActionPerformed(evt);
            }
        });
        add(minAgejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 150, 43, -1));

        jLabel7.setText("Max. Age");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 153, -1, -1));

        maxAgejTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxAgejTextField2ActionPerformed(evt);
            }
        });
        add(maxAgejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 150, 35, -1));

        jLabel8.setText("Set Age Range");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 153, -1, -1));

        jLabel9.setText("AdSpace Position");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 115, -1, -1));

        positionjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(positionjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 112, 200, -1));

        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 529, -1, -1));

        hobbiesjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(hobbiesjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 188, 132, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/AdvertiserMarketing/Real_Time_Bidding.jpg"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 44, 318, 389));

        jLabel13.setText("Publisher");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 75, 82, 20));

        publisherjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        publisherjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherjComboBox1ActionPerformed(evt);
            }
        });
        add(publisherjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 75, 200, -1));
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 228, -1, 42));

        lastSearchedjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(lastSearchedjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 273, 200, -1));

        jLabel15.setText("Category");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 276, 79, -1));

        jLabel16.setText("Quality Score");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 324, -1, -1));

        jLabel17.setText("Min Score");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 324, -1, -1));

        minScorejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minScorejTextField1ActionPerformed(evt);
            }
        });
        add(minScorejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 321, 37, -1));

        jLabel18.setText("Max Score");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 324, -1, -1));

        maxScorejTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxScorejTextField2ActionPerformed(evt);
            }
        });
        add(maxScorejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 321, 37, -1));

        jLabel3.setText("Country");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 241, 79, -1));

        countryjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(countryjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 235, 199, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bidAmountjTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidAmountjTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidAmountjTextField5ActionPerformed

    private void setBidjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBidjButton1ActionPerformed
        // TODO add your handling code here:
        String filepath = null;
        String filepath1 = null;
        String filepath2 = null;
        String filepath3 = null;

        try {
            AdSpace adSpace = (AdSpace) positionjComboBox1.getSelectedItem();
            String position = adSpace.getPosition();
            int minAge = Integer.parseInt(minAgejTextField1.getText());
            int maxAge = Integer.parseInt(maxAgejTextField2.getText());
          //  int minClick = Integer.parseInt(minClickjTextField3.getText());
           // int maxClick = Integer.parseInt(maxClickjTextField1.getText());
            String hobbies = (String) hobbiesjComboBox1.getSelectedItem();
            //int clicks = Integer.parseInt(minClickjTextField3.getText());
            
            String country = (String) countryjComboBox1.getSelectedItem();
            
            String search = (String) lastSearchedjComboBox1.getSelectedItem();
            int minScore = Integer.parseInt(minScorejTextField1.getText());
            int maxScore = Integer.parseInt(maxScorejTextField2.getText());
            Publisher publisher = (Publisher) publisherjComboBox1.getSelectedItem();
            String publisherName = publisher.getName();
            int bidAmount = Integer.parseInt(bidAmountjTextField5.getText());
            String advertiserName = advertiser.getName();
            
            
            
            if (position.equals("RightBottom")) {
                filepath1 = filepathjTextField1.getText();
            } else if (position.equals("TopRight")) {
                filepath = filepathjTextField1.getText();
            } else if (position.equals("Center")) {
                filepath2 = filepathjTextField1.getText();
            } else if (position.equals("LeftBottom")) {
                filepath3 = filepathjTextField1.getText();
            }
            
             if(Validation.checkInteger(minAgejTextField1.getText())==false ||Validation.checkInteger(maxAgejTextField2.getText())==false
                    
                     || Validation.checkInteger(bidAmountjTextField5.getText())==false){
                 JOptionPane.showMessageDialog(null,"Please enter only Integer values");
                 return;
             }
            

            if (adSpace == null || publisher == null || search == null || minAgejTextField1.getText().equals("") || maxAgejTextField2.getText().equals("") 
                     || bidAmountjTextField5.equals("") || filepathjTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill all the values");
                return;
            }
            
            if(minAge <= 0 || maxAge <=0 || minScore <0 || maxScore<0 || bidAmount <=0 ){
                JOptionPane.showMessageDialog(null,"Values cannot be negative or equal to zero");
                return;
            }
           
               /*
            for (AdSpace ad : publisher.getSsp().getAdSpaceList()) {
                if (ad.getPosition().equals("TopRight")) {
                    if (bidAmount < ad.getPrice()) {
                        JOptionPane.showMessageDialog(null, "BidAmount is lower than base price " + ad.getPrice());
                        return;
                    }
                } else if (ad.getPosition().equals("RightBottom")) {
                    if (bidAmount < ad.getPrice()) {
                        JOptionPane.showMessageDialog(null, "BidAmount is lower than base price " + ad.getPrice());
                        return;
                    }
                } else if (ad.getPosition().equals("Center")) {
                    if (bidAmount < ad.getPrice()) {
                        JOptionPane.showMessageDialog(null, "BidAmount is lower than base price " + ad.getPrice());
                        return;
                    }
                } else if (ad.getPosition().equals("LeftBottom")) {
                    if (bidAmount < ad.getPrice()) {
                        JOptionPane.showMessageDialog(null, "BidAmount is lower than base price " + ad.getPrice());
                        return;
                    }
                }
            }
                       */

        advertiser.getDsp().addBidValues(position, minAge, maxAge, hobbies,country, bidAmount, search,minScore , maxScore, userAccount, advertiserName, publisherName, filepath, filepath1, filepath2, filepath3);
        
        JOptionPane.showMessageDialog(null,"Bidding Rule Set");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter valid data");
        }
        
        
    }//GEN-LAST:event_setBidjButton1ActionPerformed

    private void filepathjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filepathjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filepathjTextField1ActionPerformed

    private void browsejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsejButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        filepathjTextField1.setText(filename);
    }//GEN-LAST:event_browsejButton1ActionPerformed

    private void minAgejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minAgejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minAgejTextField1ActionPerformed

    private void maxAgejTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxAgejTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxAgejTextField2ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void publisherjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherjComboBox1ActionPerformed
        // TODO add your handling code here:

        Publisher p = (Publisher) publisherjComboBox1.getSelectedItem();
        if (p != null) {
            populatePositionCombo(p);
        }
    }//GEN-LAST:event_publisherjComboBox1ActionPerformed

    private void minScorejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minScorejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minScorejTextField1ActionPerformed

    private void maxScorejTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxScorejTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxScorejTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JTextField bidAmountjTextField5;
    private javax.swing.JButton browsejButton1;
    private javax.swing.JComboBox countryjComboBox1;
    private javax.swing.JTextField filepathjTextField1;
    private javax.swing.JComboBox hobbiesjComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox lastSearchedjComboBox1;
    private javax.swing.JTextField maxAgejTextField2;
    private javax.swing.JTextField maxScorejTextField2;
    private javax.swing.JTextField minAgejTextField1;
    private javax.swing.JTextField minScorejTextField1;
    private javax.swing.JComboBox positionjComboBox1;
    private javax.swing.JComboBox publisherjComboBox1;
    private javax.swing.JButton setBidjButton1;
    // End of variables declaration//GEN-END:variables
}
