/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AdvertiserMarketing;

import Business.Validation.Validation;
import business.EcoSystem;
import business.Exchange.AdSpace;
import business.Exchange.Bid;
import business.Organization.DemandSidePlatform;
import business.enterprise.AdExchange;
import business.enterprise.Advertiser;
import business.enterprise.Enterprise;
import business.enterprise.Publisher;
import business.network.Network;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Krush
 */
public class UpdateBiddingRule extends javax.swing.JPanel {

    /**
     * Creates new form UpdateBiddingRule
     */
    private JPanel userProcessContainer;
    private Bid bid;
    private DemandSidePlatform organization;
    private Advertiser advertiser;
    private UserAccount userAccount;
    private EcoSystem system;

    public UpdateBiddingRule(JPanel userProcessContainer, Bid bid, DemandSidePlatform organization, Advertiser enterprise, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.bid = bid;
        this.organization = organization;
        this.advertiser = enterprise;
        this.system = system;

        minAgejTextField1.setEnabled(false);
        maxAgejTextField2.setEnabled(false);
       // minClickjTextField3.setEnabled(false);
        //maxClickjTextField1.setEnabled(false);
        bidAmountjTextField5.setEnabled(false);
        filepathjTextField1.setEnabled(false);
        minScorejTextField1.setEnabled(false);
        maxScorejTextField2.setEnabled(false);

        savejButton1.setEnabled(false);

        minAgejTextField1.setText(String.valueOf(bid.getMinAge()));
        maxAgejTextField2.setText(String.valueOf(bid.getMaxAge()));
       // minClickjTextField3.setText(String.valueOf(bid.getMinClick()));
        //maxClickjTextField1.setText(String.valueOf(bid.getMaxClick()));
        bidAmountjTextField5.setText(String.valueOf(bid.getBidAmount()));
        minScorejTextField1.setText(String.valueOf(bid.getMinScore()));
        maxScorejTextField2.setText(String.valueOf(bid.getMaxScore()));

        if (bid.getPosition().equals("RightBottom")) {
            filepathjTextField1.setText(String.valueOf(bid.getFilepath1()));
        } else if (bid.getPosition().equals("TopRight")) {
            filepathjTextField1.setText(String.valueOf(bid.getFilepath()));
        } else if (bid.getPosition().equals("Center")) {
            filepathjTextField1.setText(String.valueOf(bid.getFilepath2()));
        } else if (bid.getPosition().equals("LeftBottom")) {
            filepathjTextField1.setText(String.valueOf(bid.getFilepath3()));
        }

        populateCombobox();
    }

    public void populateCombobox() {
        positionjComboBox1.removeAllItems();
        hobbiesjComboBox1.removeAllItems();
        publisherjComboBox1.removeAllItems();
        searchjComboBox1.removeAllItems();
        countryjComboBox1.removeAllItems();
        
        /*
         for(Network n: system.getNetworkList()){
         for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
         if(e instanceof AdExchange){
         AdExchange ax =(AdExchange) e;
         for(Publisher p : ax.getPublisherList()){
         publisherjComboBox1.addItem(p);
         }
         }
         }
         }
         */
        publisherjComboBox1.addItem(bid.getPublisherName());
        searchjComboBox1.addItem(bid.getLastSearched());
        positionjComboBox1.addItem(bid.getPosition());
        hobbiesjComboBox1.addItem(bid.getHobbies());
        countryjComboBox1.addItem(bid.getCountry());

        /* 
         String adSpace[] = {"Top Right","Right Bottom"};
         for(int i = 0; i<adSpace.length; i++){
         positionjComboBox1.addItem(adSpace[i]);
            
           
         String hobbies[] = {"Sports","Music","Reading"};
         for(int j = 0; j<hobbies.length; j++){
         hobbiesjComboBox1.addItem(hobbies[j]);
         }
         }
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        browsejButton1 = new javax.swing.JButton();
        filepathjTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        minAgejTextField1 = new javax.swing.JTextField();
        hobbiesjComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        bidAmountjTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        positionjComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        maxAgejTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        savejButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        publisherjComboBox1 = new javax.swing.JComboBox();
        backjButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        searchjComboBox1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        minScorejTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        maxScorejTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        countryjComboBox1 = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("BidAmount");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 335, -1, -1));

        browsejButton1.setText("Browse");
        browsejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsejButton1ActionPerformed(evt);
            }
        });
        add(browsejButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 370, 82, -1));

        filepathjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filepathjTextField1ActionPerformed(evt);
            }
        });
        add(filepathjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 371, 190, -1));

        jLabel1.setText("Min. Age");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 140, -1, -1));

        jLabel2.setText("Hobbies");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 181, 82, -1));

        minAgejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minAgejTextField1ActionPerformed(evt);
            }
        });
        add(minAgejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 137, 43, -1));

        hobbiesjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(hobbiesjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 175, 190, -1));

        jLabel8.setText("Set Age Range");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 140, -1, -1));

        bidAmountjTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidAmountjTextField5ActionPerformed(evt);
            }
        });
        add(bidAmountjTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 332, 190, -1));

        jLabel9.setText("AdSpace Position");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 111, -1, -1));

        positionjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        positionjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionjComboBox1ActionPerformed(evt);
            }
        });
        add(positionjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 108, 190, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bid Values");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 11, -1, -1));
        add(maxAgejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 137, 39, -1));

        jLabel6.setText("Max Age");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 140, -1, -1));

        savejButton1.setText("Save");
        savejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButton1ActionPerformed(evt);
            }
        });
        add(savejButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 443, 65, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 443, 111, -1));

        jLabel11.setText("Publisher");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 80, 82, -1));

        publisherjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        publisherjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherjComboBox1ActionPerformed(evt);
            }
        });
        add(publisherjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 77, 190, -1));

        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 560, 82, -1));

        jLabel12.setText("Category");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 262, -1, -1));

        searchjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(searchjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 256, 190, -1));

        jLabel13.setText("Quality Score");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 297, 82, -1));

        jLabel14.setText("Min Score");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 297, 50, -1));
        add(minScorejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 294, 42, -1));

        jLabel15.setText("Max Score");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 297, -1, -1));
        add(maxScorejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 294, 36, -1));

        jLabel3.setText("Country");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 216, 83, -1));

        countryjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(countryjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 213, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void browsejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsejButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        filepathjTextField1.setText(filename);
    }//GEN-LAST:event_browsejButton1ActionPerformed

    private void filepathjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filepathjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filepathjTextField1ActionPerformed

    private void minAgejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minAgejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minAgejTextField1ActionPerformed

    private void bidAmountjTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidAmountjTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidAmountjTextField5ActionPerformed

    private void positionjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionjComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int dialogButton = JOptionPane.showConfirmDialog(null, "Do you want to Change the Rule?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            minAgejTextField1.setEnabled(true);
            maxAgejTextField2.setEnabled(true);
          //  minClickjTextField3.setEnabled(true);
           // maxClickjTextField1.setEnabled(true);
            bidAmountjTextField5.setEnabled(true);
            filepathjTextField1.setEnabled(true);
            savejButton1.setEnabled(true);
            minScorejTextField1.setEnabled(true);
            maxScorejTextField2.setEnabled(true);
            return;
        } else if (dialogButton == JOptionPane.NO_OPTION) {
            minAgejTextField1.setEnabled(false);
            maxAgejTextField2.setEnabled(false);
           // minClickjTextField3.setEnabled(false);
            //maxClickjTextField1.setEnabled(false);
            bidAmountjTextField5.setEnabled(false);
            filepathjTextField1.setEnabled(false);
            savejButton1.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void savejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButton1ActionPerformed
        // TODO add your handling code here:
        String filepath = null;
        String filepath1 = null;
        String filepath2 = null;
        String filepath3 = null;
        
        
       

        if (Validation.checkInteger(minAgejTextField1.getText()) == false || Validation.checkInteger(maxAgejTextField2.getText()) == false
               || Validation.checkInteger(minScorejTextField1.getText())==false || Validation.checkInteger(maxScorejTextField2.getText())==false
                || Validation.checkInteger(bidAmountjTextField5.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Please enter only Integer values");
            return;
        }
        
        
        
        
        String position = (String) positionjComboBox1.getSelectedItem();
        int minAge = Integer.parseInt(minAgejTextField1.getText());
        int maxAge = Integer.parseInt(maxAgejTextField2.getText());
      //  int minClick = Integer.parseInt(minClickjTextField3.getText());
       // int maxClick = Integer.parseInt(maxClickjTextField1.getText());
        String hobbies = (String) hobbiesjComboBox1.getSelectedItem();
        //int clicks = Integer.parseInt(minClickjTextField3.getText());
        
        String country = (String) countryjComboBox1.getSelectedItem();
        String search = (String) searchjComboBox1.getSelectedItem();

        int minScore = Integer.parseInt(minScorejTextField1.getText());
        int maxScore = Integer.parseInt(maxScorejTextField2.getText());
        String publisher = (String) publisherjComboBox1.getSelectedItem();
        int bidAmount = Integer.parseInt(bidAmountjTextField5.getText());
        
        String advertiserName = advertiser.getName();

        if (position.equals("RightBottom")) {
            filepath1 = filepathjTextField1.getText();
        } else if (position.equals("TopRight")) {
            filepath = filepathjTextField1.getText();
        } else if (position.equals("Center")) {
            filepath2 = filepathjTextField1.getText();
        } else if (position.equals("LeftBottom")) {
            filepath3 = filepathjTextField1.getText();
        }

       
          if (position == null || publisher == null || minAgejTextField1.getText().equals("") || maxAgejTextField2.getText().equals("") 
                 || bidAmountjTextField5.equals("") || filepathjTextField1.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all the values");
            return;
        }

           if(minAge <= 0 || maxAge <=0 || minScore <0 || maxScore<0 || bidAmount <=0 ){
                JOptionPane.showMessageDialog(null,"Values cannot be negative or equal to zero");
                return;
            }
           
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof AdExchange) {
                    AdExchange ax = (AdExchange) e;
                    for (Publisher p : ax.getPublisherList()) {
                        if (p.getName().equals(publisher)) {
                            for (AdSpace ad : p.getSsp().getAdSpaceList()) {
                                if (ad.getPosition().equals("TopRight")) {
                                    if (bidAmount < ad.getPrice()) {
                                        JOptionPane.showMessageDialog(null, "BidAmount is lower than base price " + ad.getPrice());
                                        return;
                                    }
                                } else if (ad.getPosition().equals("RightBottom")) {
                                    if (bidAmount < ad.getPrice()) {
                                        JOptionPane.showMessageDialog(null, "BidAmount is lower than base price " + ad.getPrice());
                                        return;
                                    }
                                } else if (ad.getPosition().equals("Center")) {
                                    if (bidAmount < ad.getPrice()) {
                                        JOptionPane.showMessageDialog(null, "BidAmount is lower than base price " + ad.getPrice());
                                        return;
                                    }
                                } else if (ad.getPosition().equals("LeftBottom")) {
                                    if (bidAmount < ad.getPrice()) {
                                        JOptionPane.showMessageDialog(null, "BidAmount is lower than base price " + ad.getPrice());
                                        return;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        bid.setPublisherName(publisher);
        bid.setPosition(position);
        bid.setMinAge(minAge);
        bid.setMaxAge(maxAge);
     //   bid.setMinClick(minClick);
      //  bid.setMaxClick(maxClick);
        bid.setHobbies(hobbies);
        
        bid.setCountry(country);

        bid.setBidAmount(bidAmount);
        bid.setLastSearched(search);
        
        

        bid.setMinScore(minScore);
        bid.setMaxScore(maxScore);

        bid.setFilepath(filepath);
        bid.setFilepath1(filepath1);
        bid.setFilepath2(filepath2);
        bid.setFilepath3(filepath3);
        //advertiser.getDsp().addBidValues(position,minAge,maxAge,hobbies, minClick,maxClick, bidAmount,userAccount, advertiserName,filepath,filepath1);
        minAgejTextField1.setEnabled(false);
        maxAgejTextField2.setEnabled(false);
     //   minClickjTextField3.setEnabled(false);
      //  maxClickjTextField1.setEnabled(false);
        bidAmountjTextField5.setEnabled(false);
        filepathjTextField1.setEnabled(false);
        savejButton1.setEnabled(false);
        minScorejTextField1.setEnabled(false);
        maxScorejTextField2.setEnabled(false);
    }//GEN-LAST:event_savejButton1ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void publisherjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherjComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JTextField bidAmountjTextField5;
    private javax.swing.JButton browsejButton1;
    private javax.swing.JComboBox countryjComboBox1;
    private javax.swing.JTextField filepathjTextField1;
    private javax.swing.JComboBox hobbiesjComboBox1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField maxAgejTextField2;
    private javax.swing.JTextField maxScorejTextField2;
    private javax.swing.JTextField minAgejTextField1;
    private javax.swing.JTextField minScorejTextField1;
    private javax.swing.JComboBox positionjComboBox1;
    private javax.swing.JComboBox publisherjComboBox1;
    private javax.swing.JButton savejButton1;
    private javax.swing.JComboBox searchjComboBox1;
    // End of variables declaration//GEN-END:variables
}
