/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.AdvertiserMarketing;

import business.EcoSystem;
import business.Exchange.Bid;
import business.Organization.DemandSidePlatform;
import business.enterprise.Advertiser;
import business.enterprise.Enterprise;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krush
 */
public class ViewBiddingModel extends javax.swing.JPanel {

    /**
     * Creates new form ViewBiddingModel
     */
     private JPanel userProcessContainer;
    private UserAccount userAccount;
    private DemandSidePlatform organization;
    private Advertiser advertiser;
    private EcoSystem system;
    public ViewBiddingModel(JPanel userProcessContainer, UserAccount userAccount, DemandSidePlatform organization, Advertiser enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.advertiser = enterprise;
        this.system = system;
        
        namejLabel2.setText(enterprise.getName());
        
        populateBidTable();
    }

    public void populateBidTable(){
        DefaultTableModel dtm = (DefaultTableModel) bidjTable1.getModel();
        dtm.setRowCount(0);
        
        for(Bid b : advertiser.getDsp().getBidList()){
            Object row[]= new Object[10];
            row[0]= b;
            row[1]= b.getPosition();
            row[2]= b.getMinAge();
            row[3]= b.getMaxAge();
            row[4]= b.getHobbies();
            row[5]= b.getCountry();
            row[6]= b.getLastSearched();
            row[7]= b.getMinScore();
            row[8]= b.getMaxScore();
            
            row[9]= b.getBidAmount();
            dtm.addRow(row);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bidjTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        deletejButton3 = new javax.swing.JButton();
        refreshjButton3 = new javax.swing.JButton();
        namejLabel2 = new javax.swing.JLabel();

        bidjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Publisher", "Ad Position", "Min Age", "Max Age", "Hobbies", "Country", "Searched", "Min Score", "Max Score", "Bid Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bidjTable1);

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Bidding Rules");

        jButton2.setText("Update Rule");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        deletejButton3.setText("Delete Rule");
        deletejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButton3ActionPerformed(evt);
            }
        });

        refreshjButton3.setText("Refresh");
        refreshjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButton3ActionPerformed(evt);
            }
        });

        namejLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namejLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jButton1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(refreshjButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(101, 101, 101)
                                    .addComponent(deletejButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namejLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(deletejButton3)
                    .addComponent(refreshjButton3))
                .addGap(105, 105, 105)
                .addComponent(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = bidjTable1.getSelectedRow();
        
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please Select a Row");
        }
        
        Bid bid = (Bid) bidjTable1.getValueAt(selectedRow,0);
        
        
        UpdateBiddingRule ubr = new UpdateBiddingRule(userProcessContainer,bid,organization, advertiser,userAccount, system);
        userProcessContainer.add("UpdateBiddingRule", ubr);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deletejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButton3ActionPerformed
        // TODO add your handling code here:
        
         int selectedRow = bidjTable1.getSelectedRow();
        
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please Select a Row");
        }
        
        Bid bid = (Bid) bidjTable1.getValueAt(selectedRow,0);
        
        advertiser.getDsp().removeBid(bid);
        
        populateBidTable();
    }//GEN-LAST:event_deletejButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void refreshjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButton3ActionPerformed
        // TODO add your handling code here:
        populateBidTable();
    }//GEN-LAST:event_refreshjButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bidjTable1;
    private javax.swing.JButton deletejButton3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namejLabel2;
    private javax.swing.JButton refreshjButton3;
    // End of variables declaration//GEN-END:variables
}
