/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.SystemAdminRole;

import business.EcoSystem;
import business.Organization.Organization;
import business.enterprise.Enterprise;
import business.network.Network;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Krush
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    
     private JPanel userProcessContainer;
    private EcoSystem system;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        //selectedNodejLabel1.setText(" ");
        populateJTree();
       
        
        
    }
         
             private void populateJTree(){
        DefaultTreeModel model = (DefaultTreeModel) systemjTree1.getModel();
        ArrayList<Network> networkList = system.getNetworkList();
        ArrayList<Enterprise>  enterpriseList;
        ArrayList<Organization> organizationList;
        
        Network network;
        Enterprise enterprise;
        Organization organization;
        
        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.insert(networks, 0);
        
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
        //entire network in system
        for(int i=0; i<networkList.size();i++){
            network = networkList.get(i);
            networkNode = new DefaultMutableTreeNode (network.getName());
            networks.insert(networkNode, i);
            
            enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();
            
           //entire enterprise in network 
            for(int j=0; j<enterpriseList.size();j++){
                enterprise = enterpriseList.get(j);
                enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode, j);
                
                organizationList = enterprise.getOrganizationDir().getOrganizationList();
              
                //entire organization in enterprise
                for(int k=0; k<organizationList.size();k++){
                    organization = organizationList.get(k);
                    
                    organizationNode = new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.insert(organizationNode, k);
                }
            }
        }
        model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        systemjTree1 = new javax.swing.JTree();
        manageNetworkjButton1 = new javax.swing.JButton();
        manageEnterpriseAdminjButton2 = new javax.swing.JButton();
        manageEnterprisejButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        manageCustomersjButton1 = new javax.swing.JButton();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        systemjTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(systemjTree1);

        manageNetworkjButton1.setText("Manage Network");
        manageNetworkjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkjButton1ActionPerformed(evt);
            }
        });

        manageEnterpriseAdminjButton2.setText("Manage Enterprise Admin");
        manageEnterpriseAdminjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseAdminjButton2ActionPerformed(evt);
            }
        });

        manageEnterprisejButton3.setText("Manage Enterprise");
        manageEnterprisejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterprisejButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("System Admin Work Area");

        manageCustomersjButton1.setText("Manage Customers");
        manageCustomersjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomersjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageNetworkjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageEnterpriseAdminjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageEnterprisejButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageCustomersjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(85, 85, 85)
                .addComponent(manageNetworkjButton1)
                .addGap(29, 29, 29)
                .addComponent(manageEnterprisejButton3)
                .addGap(32, 32, 32)
                .addComponent(manageEnterpriseAdminjButton2)
                .addGap(26, 26, 26)
                .addComponent(manageCustomersjButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageNetworkjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkjButton1ActionPerformed
        // TODO add your handling code here:
          ManageNetwork mn = new ManageNetwork(userProcessContainer,system);
        userProcessContainer.add("ManageNetwork", mn);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkjButton1ActionPerformed

    private void manageEnterpriseAdminjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminjButton2ActionPerformed
        // TODO add your handling code here:
        
           ManageEnterpriseAdmin mea = new ManageEnterpriseAdmin (userProcessContainer,system);
        userProcessContainer.add("ManageEnterpriseAdmin", mea);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseAdminjButton2ActionPerformed

    private void manageEnterprisejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterprisejButton3ActionPerformed
        // TODO add your handling code here:
         ManageEnterprise me = new ManageEnterprise (userProcessContainer,system);
        userProcessContainer.add("ManageEnterprise", me);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterprisejButton3ActionPerformed

    private void manageCustomersjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomersjButton1ActionPerformed
        // TODO add your handling code here:
           ManageCustomer1 mc = new ManageCustomer1(userProcessContainer,system);
        userProcessContainer.add("ManageCustomer", mc);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCustomersjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageCustomersjButton1;
    private javax.swing.JButton manageEnterpriseAdminjButton2;
    private javax.swing.JButton manageEnterprisejButton3;
    private javax.swing.JButton manageNetworkjButton1;
    private javax.swing.JTree systemjTree1;
    // End of variables declaration//GEN-END:variables
}
