/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.AdvertiserFinance;

import business.EcoSystem;
import business.Organization.AdvertiserFinance;
import business.Organization.Organization;
import business.enterprise.Advertiser;
import business.enterprise.Enterprise;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Krush
 */
public class AdvertiserFinanceWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form AdvertiserfinanceWorkArea
     */
     private JPanel userProcessContainer;
    private UserAccount userAccount;
    private AdvertiserFinance organization;
    private Advertiser enterprise;
    private EcoSystem system;
    public AdvertiserFinanceWorkArea(JPanel userProcessContainer,UserAccount userAccount,AdvertiserFinance organization,Advertiser enterprise,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        
        enterprisejTextField1.setText(enterprise.getName());
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setbudgetjButton2 = new javax.swing.JButton();
        makePaymentjButton1 = new javax.swing.JButton();
        enterprisejTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        viewPerformancejButton1 = new javax.swing.JButton();

        setbudgetjButton2.setText("Set Budget");
        setbudgetjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setbudgetjButton2ActionPerformed(evt);
            }
        });

        makePaymentjButton1.setText("Make Payment");
        makePaymentjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makePaymentjButton1ActionPerformed(evt);
            }
        });

        enterprisejTextField1.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Finance Work Area");

        viewPerformancejButton1.setText("View Performance");
        viewPerformancejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPerformancejButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(enterprisejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(setbudgetjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(makePaymentjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(viewPerformancejButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(enterprisejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(setbudgetjButton2)
                .addGap(52, 52, 52)
                .addComponent(makePaymentjButton1)
                .addGap(49, 49, 49)
                .addComponent(viewPerformancejButton1)
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setbudgetjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setbudgetjButton2ActionPerformed
        // TODO add your handling code here:
          SetBudgetJPanel sb = new SetBudgetJPanel(userProcessContainer,userAccount,organization,enterprise,system);
        userProcessContainer.add("SetBudget",sb);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_setbudgetjButton2ActionPerformed

    private void makePaymentjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makePaymentjButton1ActionPerformed
        // TODO add your handling code here:
         PaymentTransactionJPanel ptjp = new PaymentTransactionJPanel(userProcessContainer,userAccount,organization,enterprise,system);
        userProcessContainer.add("PaymentTransactionJPanel",ptjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_makePaymentjButton1ActionPerformed

    private void viewPerformancejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPerformancejButton1ActionPerformed
        // TODO add your handling code here:
             ViewPerformance vp = new ViewPerformance(userProcessContainer,userAccount,organization,enterprise,system);
        userProcessContainer.add("PaymentTransactionJPanel",vp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewPerformancejButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enterprisejTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton makePaymentjButton1;
    private javax.swing.JButton setbudgetjButton2;
    private javax.swing.JButton viewPerformancejButton1;
    // End of variables declaration//GEN-END:variables
}
