/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.AdvertiserFinance;

import Business.Validation.Validation;
import business.EcoSystem;
import business.Organization.AdvertiserFinance;
import business.Organization.Organization;
import business.enterprise.Advertiser;
import business.enterprise.Enterprise;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Krush
 */
public class SetBudgetJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SetBudgetJPanel
     */
        private JPanel userProcessContainer;
    private UserAccount userAccount;
    private AdvertiserFinance organization;
    private Advertiser enterprise;
    private EcoSystem system;
    private int remBudget;
    public SetBudgetJPanel(JPanel userProcessContainer,UserAccount userAccount,AdvertiserFinance organization,Advertiser enterprise,EcoSystem system) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        
        populateFields();
        
        enterpriseNamejTextField1.setText(enterprise.getName());
        remBudgetjTextField1.setText(String.valueOf(enterprise.getBudget().getRemBudget()));
        emailjTextField1.setText(enterprise.getBudget().getEmail());
        
        remBudget = enterprise.getBudget().getRemBudget();
        
        allocatejButton1.setEnabled(false);
        emailjTextField1.setEnabled(false);
        
    }
  public void populateFields(){
         amountjTextField2.setEnabled(false);
        enterpriseNamejTextField1.setText(enterprise.getName());
        remBudgetjTextField1.setText(String.valueOf(enterprise.getBudget().getRemBudget()));
        emailjTextField1.setText(enterprise.getBudget().getEmail());
        remBudget = enterprise.getBudget().getRemBudget();
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enterpriseNamejTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        amountjTextField2 = new javax.swing.JTextField();
        allocatejButton1 = new javax.swing.JButton();
        backjButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        remBudgetjTextField1 = new javax.swing.JTextField();
        updatejButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        emailjTextField1 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Finance Work Area");

        enterpriseNamejTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseNamejTextField1.setEnabled(false);

        jLabel2.setText("Set Budget Amount");

        amountjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountjTextField2ActionPerformed(evt);
            }
        });

        allocatejButton1.setText("Allocate Budget");
        allocatejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allocatejButton1ActionPerformed(evt);
            }
        });

        backjButton2.setText("<< Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Remaining Amount");

        remBudgetjTextField1.setEditable(false);
        remBudgetjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remBudgetjTextField1ActionPerformed(evt);
            }
        });

        updatejButton2.setText("Update");
        updatejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Email ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(backjButton2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(remBudgetjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(amountjTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailjTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(updatejButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(allocatejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(amountjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addComponent(remBudgetjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emailjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allocatejButton1)
                    .addComponent(updatejButton2))
                .addGap(58, 58, 58)
                .addComponent(backjButton2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void amountjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountjTextField2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_amountjTextField2ActionPerformed

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
           userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton2ActionPerformed

    private void remBudgetjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remBudgetjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remBudgetjTextField1ActionPerformed

    private void allocatejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allocatejButton1ActionPerformed
        // TODO add your handling code here:
        
        if(amountjTextField2.getText().equals("") || emailjTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all the values");
            return;
        }
        
        if(Validation.checkInteger(amountjTextField2.getText())==false){
            JOptionPane.showMessageDialog(null, "Enter only integer values");
            return;
        }
        
        int amnt = Integer.parseInt(amountjTextField2.getText());
        
        enterprise.getBudget().setEmail(emailjTextField1.getText());
        enterprise.getBudget().setBudget(amnt);
          
        if(remBudget == 0){
          enterprise.getBudget().setRemBudget(amnt);
        }
        
        else{
            remBudget = remBudget + amnt;
             enterprise.getBudget().setRemBudget(remBudget);
        }
        
          amountjTextField2.setEnabled(false);
          emailjTextField1.setEnabled(false);
        
        populateFields();
    }//GEN-LAST:event_allocatejButton1ActionPerformed

    private void updatejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButton2ActionPerformed
        // TODO add your handling code here:
        int dialogButton =  JOptionPane.showConfirmDialog(null,"Do you want to Set Budget?","Warning",JOptionPane.YES_NO_OPTION);
        if(dialogButton == JOptionPane.YES_OPTION){
            amountjTextField2.setEnabled(true);
            allocatejButton1.setEnabled(true);
            emailjTextField1.setEnabled(true);
            return;
        }
        else if(dialogButton == JOptionPane.NO_OPTION){
            amountjTextField2.setEnabled(false);
            allocatejButton1.setEnabled(false);
            emailjTextField1.setEnabled(false);
            return;
        }
           
    }//GEN-LAST:event_updatejButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allocatejButton1;
    private javax.swing.JTextField amountjTextField2;
    private javax.swing.JButton backjButton2;
    private javax.swing.JTextField emailjTextField1;
    private javax.swing.JTextField enterpriseNamejTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField remBudgetjTextField1;
    private javax.swing.JButton updatejButton2;
    // End of variables declaration//GEN-END:variables
}
